const PIECES = {
    'ou':{
      'name':'王',
      'pointMove':[-10,-9,-8,-1,1,8,9,10],
      'straightMove':[],
      'evolve':''},
    'hisya':{
      'name':'飛',
      'pointMove':[],
      'straightMove':[-9,-1,1,9], 
      'evolve':'ryu'},
    'ryu' : {
      'name':'龍',
      'pointMove':[-10,-8,8,10],
      'straightMove':[-9,-1,1,9], 
      'evolve':''},
    'kaku':{
      'name':'角',
      'pointMove':[],
      'straightMove':[-10,-8,8,10], 
      'evolve':'uma'},
    'uma' : {
      'name':'馬',
      'pointMove':[-9,-1,1,9],
      'straightMove':[-10,-8,8,10], 
      'evolve':''},
    'kin':{
      'name':'金',
      'pointMove':[-10,-9,-8,-1,1,9],
      'straightMove':[], 
      'evolve':''},
    'gin':{
      'name':'銀',
      'pointMove':[-10,-9,-8,8,10],
      'straightMove':[], 
      'evolve':'nari-gin'},
    'nari-gin':{
      'name':'唫',
      'pointMove':[-10,-9,-8,-1,1,9],
      'straightMove':[], 
      'evolve':''},
    'kei':{
      'name':'桂',
      'pointMove':[-19,-17],
      'straightMove':[], 
      'evolve':'nari-kei'},
    'nari-kei':{
      'name':'珪',
      'pointMove':[-10,-9,-8,-1,1,9],
      'straightMove':[], 
      'evolve':''},
    'kyo':{
      'name':'香',
      'pointMove':[],
      'straightMove':[-9], 
      'evolve':'nari-kyo'},
    'nari-kyo':{
      'name':'薫',
      'pointMove':[-10,-9,-8,-1,1,9],
      'straightMove':[], 
      'evolve':''},
    'fu':{
      'name':'歩',
      'pointMove':[-9],
      'straightMove':[], 
      'evolve':'to'},
    'to':{
      'name':'と',
      'pointMove':[-10,-9,-8,-1,1,9],
      'straightMove':[], 
      'evolve':''},
    '':{
      'name':'',
      'pointMove':[],
      'straightMove':[], 
      'evolve':''},
  }

export default PIECES